/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import static javaapplication2.Login.bloc;
import javax.swing.JOptionPane;
/**
 *
 * @author rajan
 */
public class dasboard extends javax.swing.JFrame {

    /**
     * Creates new form dasboard
     */
    public dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        rSButtonHover3 = new rojerusan.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        rSButtonHover6 = new rojerusan.RSButtonHover();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 30));

        rSButtonHover1.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover1.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\home.png")); // NOI18N
        rSButtonHover1.setText("HOME");
        rSButtonHover1.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover1.setIconTextGap(35);
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 60));

        rSButtonHover2.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover2.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\logout.png")); // NOI18N
        rSButtonHover2.setText("LOGOUT");
        rSButtonHover2.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover2.setIconTextGap(35);
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 280, 60));

        rSButtonHover3.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover3.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\man.png")); // NOI18N
        rSButtonHover3.setText("PROFILE");
        rSButtonHover3.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover3.setIconTextGap(35);
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, 60));

        rSButtonHover4.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover4.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\exam (1).png")); // NOI18N
        rSButtonHover4.setText("EXAM");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover4.setIconTextGap(35);
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 60));

        rSButtonHover5.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover5.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\feedback.png")); // NOI18N
        rSButtonHover5.setText("FEEDBACK");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover5.setIconTextGap(35);
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 280, 60));

        rSButtonHover6.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonHover6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 102, 153)));
        rSButtonHover6.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\certification.png")); // NOI18N
        rSButtonHover6.setText("RESULT");
        rSButtonHover6.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonHover6.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonHover6.setIconTextGap(35);
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 280, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 690));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 20, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1030, 690));

        setSize(new java.awt.Dimension(1336, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        // TODO add your handling code here:
        Login lg=new Login();
                lg.show();
                dispose();
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        // TODO add your handling code here
        uprofilr upr=new uprofilr();
        upr.show();
        dispose();
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here
        examon hm=new examon();
                  hm.show();
                  dispose();
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        // TODO add your handling code here
        if(bloc==0){
        resullt res=new resullt();
        res.show();
        dispose();}
        else{
           JOptionPane.showMessageDialog(this,"You are not eligible to give this exam");
        }
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        homepage hmp=new homepage();
        hmp.show();
        dispose();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private rojerusan.RSButtonHover rSButtonHover1;
    private rojerusan.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSButtonHover rSButtonHover6;
    // End of variables declaration//GEN-END:variables
}
