/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import static javaapplication2.Login.uid;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author rajan
 */
public class examon extends javax.swing.JFrame {

    /**
     * Creates new form examon
     */
     Connection con;
Statement st;
 String str;
ResultSet rs;
int tt=1800;
int qna=0;
int ri;
Timer time=new Timer(1000, new ActionListener() {
       
        public void actionPerformed(ActionEvent e) {
           tt--;
           if(tt>=0)
           {
               int m=0,sec=0;
               m=tt/60;
               sec=tt-(m*60);
              if(sec>9)
               tim.setText("0"+m+":"+sec);
              else
                  tim.setText("0"+m+":0"+sec);
           }
           else
           {
               dispose();
           }
               
        }
    });
{
    
}
    public examon() {
        initComponents();
        serverconnection();
        firstrecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jPanel2 = new javax.swing.JPanel();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        j5 = new necesario.RSMaterialButtonCircle();
        j4 = new necesario.RSMaterialButtonCircle();
        j3 = new necesario.RSMaterialButtonCircle();
        j2 = new necesario.RSMaterialButtonCircle();
        j1 = new necesario.RSMaterialButtonCircle();
        j6 = new necesario.RSMaterialButtonCircle();
        j7 = new necesario.RSMaterialButtonCircle();
        j8 = new necesario.RSMaterialButtonCircle();
        j9 = new necesario.RSMaterialButtonCircle();
        j10 = new necesario.RSMaterialButtonCircle();
        j11 = new necesario.RSMaterialButtonCircle();
        j15 = new necesario.RSMaterialButtonCircle();
        j13 = new necesario.RSMaterialButtonCircle();
        j14 = new necesario.RSMaterialButtonCircle();
        j12 = new necesario.RSMaterialButtonCircle();
        j20 = new necesario.RSMaterialButtonCircle();
        j19 = new necesario.RSMaterialButtonCircle();
        j17 = new necesario.RSMaterialButtonCircle();
        j16 = new necesario.RSMaterialButtonCircle();
        j18 = new necesario.RSMaterialButtonCircle();
        j21 = new necesario.RSMaterialButtonCircle();
        j24 = new necesario.RSMaterialButtonCircle();
        j25 = new necesario.RSMaterialButtonCircle();
        j23 = new necesario.RSMaterialButtonCircle();
        j22 = new necesario.RSMaterialButtonCircle();
        j26 = new necesario.RSMaterialButtonCircle();
        j27 = new necesario.RSMaterialButtonCircle();
        j28 = new necesario.RSMaterialButtonCircle();
        j29 = new necesario.RSMaterialButtonCircle();
        j30 = new necesario.RSMaterialButtonCircle();
        j31 = new necesario.RSMaterialButtonCircle();
        j32 = new necesario.RSMaterialButtonCircle();
        j33 = new necesario.RSMaterialButtonCircle();
        j34 = new necesario.RSMaterialButtonCircle();
        j35 = new necesario.RSMaterialButtonCircle();
        j36 = new necesario.RSMaterialButtonCircle();
        j37 = new necesario.RSMaterialButtonCircle();
        j38 = new necesario.RSMaterialButtonCircle();
        j39 = new necesario.RSMaterialButtonCircle();
        j40 = new necesario.RSMaterialButtonCircle();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage1.setIcon(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\college logo.png")); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.add(jrb1);
        jPanel2.add(jrb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        bg.add(jrb2);
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });
        jPanel2.add(jrb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        bg.add(jrb3);
        jPanel2.add(jrb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        bg.add(jrb4);
        jrb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb4ActionPerformed(evt);
            }
        });
        jPanel2.add(jrb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 102, 0));
        rSMaterialButtonRectangle1.setText("NEXT");
        rSMaterialButtonRectangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle1MouseEntered(evt);
            }
        });
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 180, 50));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(0, 102, 0));
        rSMaterialButtonRectangle3.setText("PREVIOUS");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 180, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Question No. ->");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jl1.setText("jLabel4");
        jPanel2.add(jl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("USER ID ->");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, 20));

        jl2.setText("jLabel6");
        jPanel2.add(jl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jtf1.setEditable(false);
        jtf1.setColumns(20);
        jtf1.setRows(5);
        jtf1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 0)), "Question ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Emoji", 1, 18), new java.awt.Color(0, 102, 0))); // NOI18N
        jScrollPane1.setViewportView(jtf1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 730, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 870, 670));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j5.setBackground(new java.awt.Color(255, 255, 51));
        j5.setBorder(new javax.swing.border.MatteBorder(null));
        j5.setForeground(new java.awt.Color(0, 0, 0));
        j5.setText("5");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        jPanel3.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 49, 47));

        j4.setBackground(new java.awt.Color(255, 255, 51));
        j4.setBorder(new javax.swing.border.MatteBorder(null));
        j4.setForeground(new java.awt.Color(0, 0, 0));
        j4.setText("4");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        jPanel3.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 49, 47));

        j3.setBackground(new java.awt.Color(255, 255, 51));
        j3.setBorder(new javax.swing.border.MatteBorder(null));
        j3.setForeground(new java.awt.Color(0, 0, 0));
        j3.setText("3");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        jPanel3.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 49, 47));

        j2.setBackground(new java.awt.Color(255, 255, 51));
        j2.setBorder(new javax.swing.border.MatteBorder(null));
        j2.setForeground(new java.awt.Color(0, 0, 0));
        j2.setText("2");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        jPanel3.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 49, 47));

        j1.setBackground(new java.awt.Color(255, 255, 51));
        j1.setBorder(new javax.swing.border.MatteBorder(null));
        j1.setForeground(new java.awt.Color(0, 0, 0));
        j1.setText("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        jPanel3.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 49, 47));

        j6.setBackground(new java.awt.Color(255, 255, 51));
        j6.setBorder(new javax.swing.border.MatteBorder(null));
        j6.setForeground(new java.awt.Color(0, 0, 0));
        j6.setText("6");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });
        jPanel3.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 49, 47));

        j7.setBackground(new java.awt.Color(255, 255, 51));
        j7.setBorder(new javax.swing.border.MatteBorder(null));
        j7.setForeground(new java.awt.Color(0, 0, 0));
        j7.setText("7");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });
        jPanel3.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 49, 47));

        j8.setBackground(new java.awt.Color(255, 255, 51));
        j8.setBorder(new javax.swing.border.MatteBorder(null));
        j8.setForeground(new java.awt.Color(0, 0, 0));
        j8.setText("8");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });
        jPanel3.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 49, 47));

        j9.setBackground(new java.awt.Color(255, 255, 51));
        j9.setBorder(new javax.swing.border.MatteBorder(null));
        j9.setForeground(new java.awt.Color(0, 0, 0));
        j9.setText("9");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });
        jPanel3.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 49, 47));

        j10.setBackground(new java.awt.Color(255, 255, 51));
        j10.setBorder(new javax.swing.border.MatteBorder(null));
        j10.setForeground(new java.awt.Color(0, 0, 0));
        j10.setText("10");
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        jPanel3.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 49, 47));

        j11.setBackground(new java.awt.Color(255, 255, 51));
        j11.setBorder(new javax.swing.border.MatteBorder(null));
        j11.setForeground(new java.awt.Color(0, 0, 0));
        j11.setText("11");
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });
        jPanel3.add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 49, 47));

        j15.setBackground(new java.awt.Color(255, 255, 51));
        j15.setBorder(new javax.swing.border.MatteBorder(null));
        j15.setForeground(new java.awt.Color(0, 0, 0));
        j15.setText("15");
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });
        jPanel3.add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 49, 47));

        j13.setBackground(new java.awt.Color(255, 255, 51));
        j13.setBorder(new javax.swing.border.MatteBorder(null));
        j13.setForeground(new java.awt.Color(0, 0, 0));
        j13.setText("13");
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });
        jPanel3.add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 49, 47));

        j14.setBackground(new java.awt.Color(255, 255, 51));
        j14.setBorder(new javax.swing.border.MatteBorder(null));
        j14.setForeground(new java.awt.Color(0, 0, 0));
        j14.setText("14");
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });
        jPanel3.add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 49, 47));

        j12.setBackground(new java.awt.Color(255, 255, 51));
        j12.setBorder(new javax.swing.border.MatteBorder(null));
        j12.setForeground(new java.awt.Color(0, 0, 0));
        j12.setText("12");
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });
        jPanel3.add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 49, 47));

        j20.setBackground(new java.awt.Color(255, 255, 51));
        j20.setBorder(new javax.swing.border.MatteBorder(null));
        j20.setForeground(new java.awt.Color(0, 0, 0));
        j20.setText("20");
        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });
        jPanel3.add(j20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 49, 47));

        j19.setBackground(new java.awt.Color(255, 255, 51));
        j19.setBorder(new javax.swing.border.MatteBorder(null));
        j19.setForeground(new java.awt.Color(0, 0, 0));
        j19.setText("19");
        j19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j19ActionPerformed(evt);
            }
        });
        jPanel3.add(j19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 49, 47));

        j17.setBackground(new java.awt.Color(255, 255, 51));
        j17.setBorder(new javax.swing.border.MatteBorder(null));
        j17.setForeground(new java.awt.Color(0, 0, 0));
        j17.setText("17");
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });
        jPanel3.add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 49, 47));

        j16.setBackground(new java.awt.Color(255, 255, 51));
        j16.setBorder(new javax.swing.border.MatteBorder(null));
        j16.setForeground(new java.awt.Color(0, 0, 0));
        j16.setText("16");
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });
        jPanel3.add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 49, 47));

        j18.setBackground(new java.awt.Color(255, 255, 51));
        j18.setBorder(new javax.swing.border.MatteBorder(null));
        j18.setForeground(new java.awt.Color(0, 0, 0));
        j18.setText("18");
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });
        jPanel3.add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 49, 47));

        j21.setBackground(new java.awt.Color(255, 255, 51));
        j21.setBorder(new javax.swing.border.MatteBorder(null));
        j21.setForeground(new java.awt.Color(0, 0, 0));
        j21.setText("21");
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });
        jPanel3.add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 49, 47));

        j24.setBackground(new java.awt.Color(255, 255, 51));
        j24.setBorder(new javax.swing.border.MatteBorder(null));
        j24.setForeground(new java.awt.Color(0, 0, 0));
        j24.setText("24");
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });
        jPanel3.add(j24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 49, 47));

        j25.setBackground(new java.awt.Color(255, 255, 51));
        j25.setBorder(new javax.swing.border.MatteBorder(null));
        j25.setForeground(new java.awt.Color(0, 0, 0));
        j25.setText("25");
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });
        jPanel3.add(j25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 49, 47));

        j23.setBackground(new java.awt.Color(255, 255, 51));
        j23.setBorder(new javax.swing.border.MatteBorder(null));
        j23.setForeground(new java.awt.Color(0, 0, 0));
        j23.setText("23");
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });
        jPanel3.add(j23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 49, 47));

        j22.setBackground(new java.awt.Color(255, 255, 51));
        j22.setBorder(new javax.swing.border.MatteBorder(null));
        j22.setForeground(new java.awt.Color(0, 0, 0));
        j22.setText("22");
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });
        jPanel3.add(j22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 49, 47));

        j26.setBackground(new java.awt.Color(255, 255, 51));
        j26.setBorder(new javax.swing.border.MatteBorder(null));
        j26.setForeground(new java.awt.Color(0, 0, 0));
        j26.setText("26");
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });
        jPanel3.add(j26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 49, 47));

        j27.setBackground(new java.awt.Color(255, 255, 51));
        j27.setBorder(new javax.swing.border.MatteBorder(null));
        j27.setForeground(new java.awt.Color(0, 0, 0));
        j27.setText("27");
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });
        jPanel3.add(j27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 49, 47));

        j28.setBackground(new java.awt.Color(255, 255, 51));
        j28.setBorder(new javax.swing.border.MatteBorder(null));
        j28.setForeground(new java.awt.Color(0, 0, 0));
        j28.setText("28");
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });
        jPanel3.add(j28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 49, 47));

        j29.setBackground(new java.awt.Color(255, 255, 51));
        j29.setBorder(new javax.swing.border.MatteBorder(null));
        j29.setForeground(new java.awt.Color(0, 0, 0));
        j29.setText("29");
        j29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j29ActionPerformed(evt);
            }
        });
        jPanel3.add(j29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 49, 47));

        j30.setBackground(new java.awt.Color(255, 255, 51));
        j30.setBorder(new javax.swing.border.MatteBorder(null));
        j30.setForeground(new java.awt.Color(0, 0, 0));
        j30.setText("30");
        j30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30ActionPerformed(evt);
            }
        });
        jPanel3.add(j30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 49, 47));

        j31.setBackground(new java.awt.Color(255, 255, 51));
        j31.setBorder(new javax.swing.border.MatteBorder(null));
        j31.setForeground(new java.awt.Color(0, 0, 0));
        j31.setText("31");
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });
        jPanel3.add(j31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 49, 47));

        j32.setBackground(new java.awt.Color(255, 255, 51));
        j32.setBorder(new javax.swing.border.MatteBorder(null));
        j32.setForeground(new java.awt.Color(0, 0, 0));
        j32.setText("32");
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });
        jPanel3.add(j32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 49, 47));

        j33.setBackground(new java.awt.Color(255, 255, 51));
        j33.setBorder(new javax.swing.border.MatteBorder(null));
        j33.setForeground(new java.awt.Color(0, 0, 0));
        j33.setText("33");
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });
        jPanel3.add(j33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 49, 47));

        j34.setBackground(new java.awt.Color(255, 255, 51));
        j34.setBorder(new javax.swing.border.MatteBorder(null));
        j34.setForeground(new java.awt.Color(0, 0, 0));
        j34.setText("34");
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });
        jPanel3.add(j34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 49, 47));

        j35.setBackground(new java.awt.Color(255, 255, 51));
        j35.setBorder(new javax.swing.border.MatteBorder(null));
        j35.setForeground(new java.awt.Color(0, 0, 0));
        j35.setText("35");
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });
        jPanel3.add(j35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 49, 47));

        j36.setBackground(new java.awt.Color(255, 255, 51));
        j36.setBorder(new javax.swing.border.MatteBorder(null));
        j36.setForeground(new java.awt.Color(0, 0, 0));
        j36.setText("36");
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });
        jPanel3.add(j36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 49, 47));

        j37.setBackground(new java.awt.Color(255, 255, 51));
        j37.setBorder(new javax.swing.border.MatteBorder(null));
        j37.setForeground(new java.awt.Color(0, 0, 0));
        j37.setText("37");
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });
        jPanel3.add(j37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 49, 47));

        j38.setBackground(new java.awt.Color(255, 255, 51));
        j38.setBorder(new javax.swing.border.MatteBorder(null));
        j38.setForeground(new java.awt.Color(0, 0, 0));
        j38.setText("38");
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });
        jPanel3.add(j38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 49, 47));

        j39.setBackground(new java.awt.Color(255, 255, 51));
        j39.setBorder(new javax.swing.border.MatteBorder(null));
        j39.setForeground(new java.awt.Color(0, 0, 0));
        j39.setText("39");
        j39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j39ActionPerformed(evt);
            }
        });
        jPanel3.add(j39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 49, 47));

        j40.setBackground(new java.awt.Color(255, 255, 51));
        j40.setBorder(new javax.swing.border.MatteBorder(null));
        j40.setForeground(new java.awt.Color(0, 0, 0));
        j40.setText("40");
        j40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j40ActionPerformed(evt);
            }
        });
        jPanel3.add(j40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 49, 47));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon("R:\\Drive D\\NetBeansProjects\\JavaApplication2\\src\\image\\question.png")); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Question Chart");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setText("END TIME ->");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, -1));

        tim.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        tim.setForeground(new java.awt.Color(204, 0, 0));
        tim.setText("jLabel10");
        jPanel3.add(tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 80, -1));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 102, 0));
        rSMaterialButtonRectangle2.setText("SUBMITE");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 180, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 420, 670));

        setSize(new java.awt.Dimension(1457, 876));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        try{
        rs.first();
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j1ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(6);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j6ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(11);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j11ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(16);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j16ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(21);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j21ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jrb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb4ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        // TODO add your handling code here:
         dasboard das=new dasboard();
        das.show();
        dispose();
               saveserver();
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(26);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j26ActionPerformed

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(31);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j31ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(36);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j36ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        // TODO add your handling code here:
         try
        {
            rs.previous();
            jtf1.setText(rs.getString("question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
        try
        {
            rs.next();
            jtf1.setText(rs.getString("question"));
            jl1.setText(rs.getString("No"));
            jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
                {
                    
                }
          bg.clearSelection();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(2);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(3);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(4);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(5);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j5ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(7);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(8);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(9);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(10);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j10ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(12);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j12ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(13);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j13ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(14);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(15);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j15ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(17);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j17ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(18);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j18ActionPerformed

    private void j19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j19ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(19);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j19ActionPerformed

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(20);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j20ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(22);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j22ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(23);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j23ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(24);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j24ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(25);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j25ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(27);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j27ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(28);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j28ActionPerformed

    private void j29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j29ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(29);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j29ActionPerformed

    private void j30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(30);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j30ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(32);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j32ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(33);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j33ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(34);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j34ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(35);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j35ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(37);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j37ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(38);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j38ActionPerformed

    private void j39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j39ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(39);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j39ActionPerformed

    private void j40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j40ActionPerformed
        // TODO add your handling code here:
         try{
        rs.absolute(40);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j40ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         time.start();
    }//GEN-LAST:event_formWindowOpened

    private void rSMaterialButtonRectangle1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1MouseEntered
        // TODO add your handling code here:
        try{
            
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
         saveserver();
                      
    }//GEN-LAST:event_rSMaterialButtonRectangle1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examon().setVisible(true);
            }
        });
    }
     public final void firstrecord()
{
    try
        {
            rs.first();
            jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
         
        }
        catch(Exception e)
                {
                    
                }

     
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private necesario.RSMaterialButtonCircle j1;
    private necesario.RSMaterialButtonCircle j10;
    private necesario.RSMaterialButtonCircle j11;
    private necesario.RSMaterialButtonCircle j12;
    private necesario.RSMaterialButtonCircle j13;
    private necesario.RSMaterialButtonCircle j14;
    private necesario.RSMaterialButtonCircle j15;
    private necesario.RSMaterialButtonCircle j16;
    private necesario.RSMaterialButtonCircle j17;
    private necesario.RSMaterialButtonCircle j18;
    private necesario.RSMaterialButtonCircle j19;
    private necesario.RSMaterialButtonCircle j2;
    private necesario.RSMaterialButtonCircle j20;
    private necesario.RSMaterialButtonCircle j21;
    private necesario.RSMaterialButtonCircle j22;
    private necesario.RSMaterialButtonCircle j23;
    private necesario.RSMaterialButtonCircle j24;
    private necesario.RSMaterialButtonCircle j25;
    private necesario.RSMaterialButtonCircle j26;
    private necesario.RSMaterialButtonCircle j27;
    private necesario.RSMaterialButtonCircle j28;
    private necesario.RSMaterialButtonCircle j29;
    private necesario.RSMaterialButtonCircle j3;
    private necesario.RSMaterialButtonCircle j30;
    private necesario.RSMaterialButtonCircle j31;
    private necesario.RSMaterialButtonCircle j32;
    private necesario.RSMaterialButtonCircle j33;
    private necesario.RSMaterialButtonCircle j34;
    private necesario.RSMaterialButtonCircle j35;
    private necesario.RSMaterialButtonCircle j36;
    private necesario.RSMaterialButtonCircle j37;
    private necesario.RSMaterialButtonCircle j38;
    private necesario.RSMaterialButtonCircle j39;
    private necesario.RSMaterialButtonCircle j4;
    private necesario.RSMaterialButtonCircle j40;
    private necesario.RSMaterialButtonCircle j5;
    private necesario.RSMaterialButtonCircle j6;
    private necesario.RSMaterialButtonCircle j7;
    private necesario.RSMaterialButtonCircle j8;
    private necesario.RSMaterialButtonCircle j9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JTextArea jtf1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
 private void serverconnection() 
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
                
                 st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                 str="select * from addquestions";
                 rs=st.executeQuery(str);
                               
        }    
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }
    private void answe()
    {
        
       
        
        try
        {
             int nn=0;
            Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
             st=con.createStatement();
             str="select * from useranswer";
             ResultSet rsc=st.executeQuery(str);
//             rs=st.executeQuery(str);
             {    
               nn=Integer.parseInt(rs.getString("No"));
          
                switch(nn){
                    case 1:
                        j1.setBackground(Color.BLUE);
                        break;
                    case 2:
                        j2.setBackground(Color.BLUE);
                        break;
                    case 3:
                        j3.setBackground(Color.BLUE);
                        break;
                    case 4:
                        j4.setBackground(Color.BLUE);
                        break;
                       case 5:
                        j5.setBackground(Color.BLUE);
                        break;
                        case 6:
                        j6.setBackground(Color.BLUE);
                        break;
                        case 7:
                        j7.setBackground(Color.BLUE);
                        break;
                        case 8:
                        j8.setBackground(Color.BLUE);
                        break;
                        case 9:
                        j9.setBackground(Color.BLUE);
                        break;
                        case 10:
                        j10.setBackground(Color.BLUE);
                        break;
                    case 11:
                        j11.setBackground(Color.BLUE);
                        break;
                    case 12:
                        j12.setBackground(Color.BLUE);
                        break;
                    case 13:
                        j13.setBackground(Color.BLUE);
                        break;
                    case 14:
                        j14.setBackground(Color.BLUE);
                        break;
                    case 15:
                        j15.setBackground(Color.BLUE);
                        break;
                        case 16:
                        j6.setBackground(Color.BLUE);
                        break;
                        case 17:
                        j17.setBackground(Color.BLUE);
                        break;
                        case 18:
                        j18.setBackground(Color.BLUE);
                        break;
                        case 19:
                        j19.setBackground(Color.BLUE);
                        break;
                        case 20:
                        j20.setBackground(Color.BLUE);
                        break;
                case 21:
                        j21.setBackground(Color.BLUE);
                        break;
                    case 22:
                        j2.setBackground(Color.BLUE);
                        break;
                    case 23:
                        j23.setBackground(Color.BLUE);
                        break;
                        case 24:
                        j24.setBackground(Color.BLUE);
                        break;
                       case 25:
                        j25.setBackground(Color.BLUE);
                        break;
                        case 26:
                        j26.setBackground(Color.BLUE);
                        break;
                        case 27:
                        j27.setBackground(Color.BLUE);
                        break;
                        case 28:
                        j28.setBackground(Color.BLUE);
                        break;
                        case 29:
                        j29.setBackground(Color.BLUE);
                        break;
                        case 30:
                        j30.setBackground(Color.BLUE);
                        break;
                    case 31:
                        j1.setBackground(Color.BLUE);
                        break;
                    case 32:
                        j32.setBackground(Color.BLUE);
                        break;
                    case 33:
                        j33.setBackground(Color.BLUE);
                        break;
                    case 34:
                        j34.setBackground(Color.BLUE);
                        break;
                       case 35:
                        j35.setBackground(Color.BLUE);
                        break;
                        case 36:
                        j36.setBackground(Color.BLUE);
                        break;
                        case 37:
                        j37.setBackground(Color.BLUE);
                        break;
                        case 38:
                        j38.setBackground(Color.BLUE);
                        break;
                        case 39:
                        j39.setBackground(Color.BLUE);
                        break;
                        case 40:
                        j40.setBackground(Color.BLUE);
                        break;}
                    
             }
                
       st.close();
                con.close();
                
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(this,e); 
        }
        

       
    }
    private void saveserver()
    {
        int usan=0;
        int c=0;
       if(jrb1.isSelected())
        {
           usan=1;
           answe();
          c=1;
           
        }
       if(jrb2.isSelected())
        {
             answe();
            usan=2;
            c=1;
        }
       if(jrb3.isSelected())
        {
             answe();
            usan=3;
          c=1;
        }
       if(jrb4.isSelected())
        {
             answe();
            usan=4;
            c=1;
        }

       try{
         try 
        {
            
            c=0;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
          
             
            
                 st=con.createStatement();
                st.executeUpdate("insert into useranswer values('"+uid+"','"+jl1.getText()+"','"+usan+"','"+ri+"')");
               
               
                st.close();
                con.close();
               throw new SQLIntegrityConstraintViolationException ("Duplicate entry");  
                 
        }
        catch(SQLIntegrityConstraintViolationException e)
        {
           
        }
         Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
       
      String sql="select * from useranswer where No=?";
       PreparedStatement prstm=con.prepareStatement(sql);
       prstm.setString(1,jl1.getText());
       
     
       
       ResultSet rst=prstm.executeQuery();
      
       if(rst.next())
       {
           
           
          
                prstm.executeUpdate("update useranswer set ans='"+usan+"' where No='"+jl1.getText()+"'");
            

       }
       
       con.close();
      prstm.close();
       
       }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this, e);
         }

        }

}
