/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javaapplication2.forget1;
import javaapplication2.examon;
import javaapplication2.signup;
import javax.swing.JOptionPane;

/**
 *
 * @author rajan
 */
public class Login extends javax.swing.JFrame {
static String uid;
static int bloc=0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSButtonHover3 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        jLabel9 = new javax.swing.JLabel();
        jpf1 = new rojerusan.RSPasswordTextPlaceHolder();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/permission (1).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 280, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 181, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jtf1.setForeground(new java.awt.Color(102, 102, 102));
        jtf1.setText("Enter username..........");
        jtf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf1FocusGained(evt);
            }
        });
        jtf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf1MouseClicked(evt);
            }
        });
        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });
        jPanel2.add(jtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 181, 204));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Or Login with");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gmail (3).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/instagram (3).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facebook (3).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 40, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 38)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 181, 204));
        jLabel8.setText("Login");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        rSButtonHover3.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        rSButtonHover3.setForeground(new java.awt.Color(0, 181, 204));
        rSButtonHover3.setText("Signup");
        rSButtonHover3.setColorHover(new java.awt.Color(153, 0, 51));
        rSButtonHover3.setColorText(new java.awt.Color(0, 181, 204));
        rSButtonHover3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 80, 30));

        rSButtonHover4.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        rSButtonHover4.setText("Login");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonHover4.setColorText(new java.awt.Color(0, 181, 204));
        rSButtonHover4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 70, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel9.setText("             Forgot Password");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, -1));

        jpf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpf1.setText("Enter your passowrd");
        jpf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpf1FocusGained(evt);
            }
        });
        jpf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpf1ActionPerformed(evt);
            }
        });
        jPanel2.add(jpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 640, 500));

        setSize(new java.awt.Dimension(998, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here:
         try
      {
       Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
       
       String sql="select * from signup where User_id=? and Password=?";
       PreparedStatement prstm=con.prepareStatement(sql);
       prstm.setString(1,jtf1.getText());
       prstm.setString(2,jpf1.getText());
       
       ResultSet rs=prstm.executeQuery();
       
       if(rs.next())
       {
           JOptionPane.showMessageDialog(this,"Login sucessfull","",JOptionPane.PLAIN_MESSAGE);
           uid=jtf1.getText();
           bloc=Integer.parseInt(rs.getString("Profile"));
            dasboard das=new dasboard();
                  das.show();
                  dispose();
           
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Login Unsucessfull,Please try again");
           jtf1.setText("");
           jpf1.setText("");
       }
       con.close();
       prstm.close();
       
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this, e);
      }
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        // TODO add your handling code here
          signup sg=new signup();
                  sg.show();
                  dispose();
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        forget1 frgtp=new forget1();
        frgtp.show();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jtf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf1FocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtf1FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void jtf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf1MouseClicked
        // TODO add your handling code here:
          jtf1.setText("");
    }//GEN-LAST:event_jtf1MouseClicked

    private void jpf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpf1FocusGained
        // TODO add your handling code here:
        jpf1.setText("");
    }//GEN-LAST:event_jpf1FocusGained

    private void jpf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSPasswordTextPlaceHolder jpf1;
    private javax.swing.JTextField jtf1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    // End of variables declaration//GEN-END:variables
}
